name: "Update Dev Joke of the Day"

on:
  schedule:
    - cron: "0 6 * * *"  # Runs every day at 06:00 UTC
  workflow_dispatch:

jobs:
  update-joke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch Dev Joke
        run: python .github/scripts/update_joke.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md .jokes.json
          git commit -m "chore: update Dev Joke of the Day" || echo "No changes to commit"
          git push
